#!/bin/bash

# Will be executed as user "root".

# Name this file "daemon" in your plugin-archive. It will be renamed to NAME
# during installation

loxberryhome=REPLACEINSTALLFOLDER
pluginname=REPLACEFOLDERNAME

# Directory/Pluginname fallback for test environment
if [ ! -d $loxberryhome ]; then
	loxberryhome=/opt/loxberry
fi
if [ ! -d $pluginname ]; then
	pluginname=anyplugin
fi

/usr/bin/logger "loxberry-plugin-$pluginname - DAEMON Script from Any Plugin"
	
# Add Any-Plugin to sudoers (need root permission)
# Sudoers V2
sudoversion=2

if [ ! -e $loxberryhome/config/plugins/$pluginname/sudoers.v$sudoversion ]
	then
		/usr/bin/logger "loxberry-plugin-$pluginname - Adding sudoers permissions V$sudoversion"
		echo %loxberry ALL = NOPASSWD: $loxberryhome/webfrontend/cgi/plugins/$pluginname/bin/tcp2shell2.pl > /etc/sudoers.d/$pluginname
		echo %loxberry ALL = NOPASSWD: $loxberryhome/webfrontend/cgi/plugins/$pluginname/bin/restart_tcp2shell.sh >> /etc/sudoers.d/$pluginname
		echo %loxberry ALL = NOPASSWD: /usr/bin/killall >> /etc/sudoers.d/$pluginname
		chmod 0440 /etc/sudoers.d/$pluginname
		rm $loxberryhome/config/plugins/$pluginname/sudoers.*
		echo Sudoers V$sudoversion > $loxberryhome/config/plugins/$pluginname/sudoers.v$sudoversion
fi

# Change permissions
if [ ! -x "$loxberryhome/webfrontend/cgi/plugins/$pluginname/bin/kill_tcp2shell2.sh" ]; then
	/usr/bin/logger "loxberry-plugin-$pluginname - Setting kill_tcp2shell +x permissions"
	chmod +x $loxberryhome/webfrontend/cgi/plugins/$pluginname/bin/restart_tcp2shell.sh
fi

# Config file parsing (based on http://stackoverflow.com/a/20815951/3466839)
configfile="$loxberryhome/config/plugins/$pluginname/anyplugin.cfg" # set the actual path name of your (DOS or Unix) config file
if [ -e $configfile ]; then
  mkdir /run/shm/$pluginname > /dev/null 2>&1
  chown loxberry.loxberry /run/shm/$pluginname > /dev/null 2>&1
  chmod a+w /run/shm/$pluginname > /dev/null 2>&1
  shopt -s extglob
  tr -d '\r' < $configfile > /run/shm/$pluginname/tempconfigfile.unix
  while IFS='= ' read lhs rhs
  do
      if [[ ! $lhs =~ ^\ *# && -n $lhs ]]; then
          rhs="${rhs%%\#*}"    # Del in line right comments
          rhs="${rhs%%*( )}"   # Del trailing spaces
          rhs="${rhs%\"*}"     # Del opening string quotes
          rhs="${rhs#\"*}"     # Del closing string quotes
          if [[ $lhs =~ ^\[ ]]; then # Set INI-like sections, e.g. [MAIN]
            lhs="${lhs%\]*}"     # Del opening bracket
            lhs="${lhs#\[*}"     # Del closing bracket
            sec=$lhs
          else
            if [[ ! $lhs =~ ^\; ]]; then # Don't parse comments startet with ;
              name="$sec$lhs"
              declare ${name}="$rhs"
              #echo "$name = $rhs" # for debugging only
            fi
          fi
      fi
  done < /run/shm/$pluginname/tempconfigfile.unix
  rm /run/shm/$pluginname/tempconfigfile.unix > /dev/null 2>&1
  # Config file parsing end
fi

# If runas is empty, set loxberry as user
if [ -z "$Mainrunas" ]; then
	Mainrunas = "root"
fi

chmod -R 774 $loxberryhome/data/plugins/$pluginname/commands

/usr/bin/logger "loxberry-plugin-$pluginname - Running tcp2shell with user $Mainrunas"
# This is the new IPv4/v6 code
sudo -n -u $Mainrunas -- $loxberryhome/webfrontend/cgi/plugins/$pluginname/bin/tcp2shell2.pl >>$loxberryhome/log/plugins/$pluginname/tcp2shell.log 2>&1 &
chown loxberry:loxberry $loxberryhome/log/plugins/$pluginname/tcp2shell.log
exit 0
